enum AnimalType {
    BOEUF = 'Bœuf',
    AGNEAU = 'Agneau',
    PORC = 'Porc',
    VEAU = 'Veau',
    CANARD = 'Canard',
    LAPIN = 'Lapin'
  }
  enum Unit {
    GRAMME = 'g',
    KILOGRAMME = 'kg',
    LITRE = 'l',
    MILLILITRE = 'ml',
    PIECE = 'pc'
  }
export type Ingredients = {
  name: string;
  glutenFree: boolean;
  vegetarian: boolean;
  vegan: boolean;
  lactoseFree: boolean;
  caloriesPer100g: number;
  unit: string;
}

export const ingredients = {
  fruits: [
    { name: 'Pomme', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 52, unit: Unit.GRAMME },
    { name: 'Banane', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 89, unit: Unit.GRAMME },
    { name: 'Orange', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 47, unit: Unit.GRAMME },
    { name: 'Fraise', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 33, unit: Unit.GRAMME },
    { name: 'Framboise', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 53, unit: Unit.GRAMME },
    { name: 'Myrtille', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 57, unit: Unit.GRAMME },
    { name: 'Pêche', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 39, unit: Unit.GRAMME },
    { name: 'Abricot', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 49, unit: Unit.GRAMME },
    { name: 'Poire', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 57, unit: Unit.GRAMME },
    { name: 'Raisin', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 69, unit: Unit.GRAMME },
    { name: 'Cerise', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 63, unit: Unit.GRAMME },
    { name: 'Ananas', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 50, unit: Unit.GRAMME },
    { name: 'Mangue', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 60, unit: Unit.GRAMME },
    { name: 'Kiwi', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 93, unit: Unit.GRAMME },
    { name: 'Melon', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 34, unit: Unit.GRAMME },
    { name: 'Pastèque', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 30, unit: Unit.GRAMME },
    { name: 'Citron', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 29, unit: Unit.GRAMME },
    { name: 'Lime', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 30, unit: Unit.GRAMME },
    { name: 'Pamplemousse', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 42, unit: Unit.GRAMME },
    { name: 'Grenade', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 83, unit: Unit.GRAMME }
  ],
  legumes: [
    { name: 'Carotte', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 85, unit: Unit.GRAMME },
    { name: 'Tomate', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 18, unit: Unit.GRAMME },
    { name: 'Concombre', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 15, unit: Unit.GRAMME },
    { name: 'Poivron', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 25, unit: Unit.GRAMME },
    { name: 'Aubergine', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 24, unit: Unit.GRAMME },
    { name: 'Courgette', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 17, unit: Unit.GRAMME },
    { name: 'Brocoli', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 34, unit: Unit.GRAMME },
    { name: 'Chou-fleur', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 23, unit: Unit.GRAMME },
    { name: 'Épinard', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 23, unit: Unit.GRAMME },
    { name: 'Laitue', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 11, unit: Unit.GRAMME },
    { name: 'Oignon', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 40, unit: Unit.GRAMME },
    { name: 'Ail', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 133, unit: Unit.GRAMME },
    { name: 'Pomme de terre', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 93, unit: Unit.GRAMME },
    { name: 'Patate douce', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 98, unit: Unit.GRAMME },
    { name: 'Maïs', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 108, unit: Unit.GRAMME },
    { name: 'Haricot vert', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 31, unit: Unit.GRAMME },
    { name: 'Pois', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 74, unit: Unit.GRAMME },
    { name: 'Asperge', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 20, unit: Unit.GRAMME },
    { name: 'Champignon', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 21, unit: Unit.GRAMME },
    { name: 'Betterave', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 43, unit: Unit.GRAMME },
    { name: 'Céleri', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 16, unit: Unit.GRAMME },
    { name: 'Poireau', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 61, unit: Unit.GRAMME },
    { name: 'Radis', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 14, unit: Unit.GRAMME },
    { name: 'Navet', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 22, unit: Unit.GRAMME },
    { name: 'Chou', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 25, unit: Unit.GRAMME },
    { name: 'Citrouille', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 26, unit: Unit.GRAMME },
    { name: 'Potiron', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 42, unit: Unit.GRAMME }
  ],
  viandes: [
    { name: 'Filet', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 217, unit: Unit.GRAMME },
    { name: 'Côte', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 250, unit: Unit.GRAMME },
    { name: 'Épaule', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 236, unit: Unit.GRAMME },
    { name: 'Cuisse', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 209, unit: Unit.GRAMME },
    { name: 'Poitrine', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 436, unit: Unit.GRAMME },
    { name: 'Foie', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 136, unit: Unit.GRAMME },
    { name: 'Cœur', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 112, unit: Unit.GRAMME },
    { name: 'Langue', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 224, unit: Unit.GRAMME },
    { name: 'Hachis', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 332, unit: Unit.GRAMME },
    { name: 'Jambon', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 145, unit: Unit.GRAMME },
    { name: 'Saucisse', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 301, unit: Unit.GRAMME },
    { name: 'Rôti', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 213, unit: Unit.GRAMME },
    { name: 'Escalope', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 165, unit: Unit.GRAMME },
    { name: 'Entrecôte', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 291, unit: Unit.GRAMME },
    { name: 'Lardon', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 541, unit: Unit.GRAMME },
    { name: 'Rognon', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 124, unit: Unit.GRAMME },
    { name: 'Andouillette', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 263, unit: Unit.GRAMME },
    { name: 'Boudin', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 379, unit: Unit.GRAMME },
    { name: 'Cervelle', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 125, unit: Unit.GRAMME },
    { name: 'Tripes', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 94, unit: Unit.GRAMME },
    { name: 'Gigot', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 294, unit: Unit.GRAMME },
    { name: 'Magret', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 337, unit: Unit.GRAMME },
    { name: 'Paupiette', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 220, unit: Unit.GRAMME },
    { name: 'Gésier', variety: AnimalType, glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 147, unit: Unit.GRAMME },
  ],
  poissonsEtFruitsDeMer: [
    { name: 'Saumon', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 208, unit: Unit.GRAMME },
    { name: 'Thon', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 184, unit: Unit.GRAMME },
    { name: 'Cabillaud', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 82, unit: Unit.GRAMME },
    { name: 'Crevettes', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 99, unit: Unit.GRAMME },
    { name: 'Moules', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 86, unit: Unit.GRAMME },
    { name: 'Sardines', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 208, unit: Unit.GRAMME },
    { name: 'Truite', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 141, unit: Unit.GRAMME },
    { name: 'Maquereau', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 205, unit: Unit.GRAMME },
    { name: 'Sole', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 86, unit: Unit.GRAMME },
    { name: 'Dorade', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 100, unit: Unit.GRAMME },
    { name: 'Lieu noir', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 90, unit: Unit.GRAMME },
    { name: 'Merlu', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 82, unit: Unit.GRAMME },
    { name: 'Bar', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 97, unit: Unit.GRAMME },
    { name: 'Anchois', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 131, unit: Unit.GRAMME },
    { name: 'Hareng', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 203, unit: Unit.GRAMME },
    { name: 'Huitres', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 69, unit: Unit.GRAMME },
    { name: 'Calmar', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 92, unit: Unit.GRAMME },
    { name: 'Poulpe', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 82, unit: Unit.GRAMME },
    { name: 'Homard', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 89, unit: Unit.GRAMME },
    { name: 'Crabe', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 97, unit: Unit.GRAMME }
  ],
  produitsLaitiers: [
    { name: 'Lait', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 42, unit: Unit.MILLILITRE },
    { name: 'Fromage', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 404, unit: Unit.GRAMME },
    { name: 'Yaourt', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 61, unit: Unit.GRAMME },
    { name: 'Beurre', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 729, unit: Unit.GRAMME },
    { name: 'Crème', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 340, unit: Unit.MILLILITRE },
    { name: 'Œuf', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: true, caloriesPer100g: 144, unit: Unit.GRAMME },
    { name: 'Mozzarella', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 304, unit: Unit.GRAMME },
    { name: 'Parmesan', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 436, unit: Unit.GRAMME },
    { name: 'Feta', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 268, unit: Unit.GRAMME },
    { name: 'Ricotta', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 140, unit: Unit.GRAMME },
    { name: 'Mascarpone', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 800, unit: Unit.GRAMME },
    { name: 'Crème fraîche', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 340, unit: Unit.MILLILITRE },
    { name: 'Fromage blanc', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 98, unit: Unit.GRAMME },
    { name: 'Comté', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 411, unit: Unit.GRAMME },
    { name: 'Roquefort', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 375, unit: Unit.GRAMME },
    { name: 'Camembert', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 304, unit: Unit.GRAMME },
    { name: 'Brie', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 339, unit: Unit.GRAMME }
  ],
  cerealesEtFeculents: [
    { name: 'Riz', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 130, unit: Unit.GRAMME },
    { name: 'Pâtes', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 158, unit: Unit.GRAMME },
    { name: 'Quinoa', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 120, unit: Unit.GRAMME },
    { name: 'Avoine', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 379, unit: Unit.GRAMME },
    { name: 'Blé', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 339, unit: Unit.GRAMME },
    { name: 'Orge', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 123, unit: Unit.GRAMME },
    { name: 'Semoule', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 360, unit: Unit.GRAMME },
    { name: 'Pain', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 247, unit: Unit.GRAMME },
    { name: 'Tortilla', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 298, unit: Unit.GRAMME },
    { name: 'Couscous', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 112, unit: Unit.GRAMME },
    { name: 'Boulgour', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 83, unit: Unit.GRAMME },
    { name: 'Millet', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 119, unit: Unit.GRAMME },
    { name: 'Sarrasin', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 92, unit: Unit.GRAMME },
    { name: 'Polenta', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 60, unit: Unit.GRAMME },
    { name: 'Tapioca', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 358, unit: Unit.GRAMME }
  ],
  legumineuses: [
    { name: 'Lentilles', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 116, unit: Unit.GRAMME },
    { name: 'Pois chiches', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 164, unit: Unit.GRAMME },
    { name: 'Haricots rouges', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 127, unit: Unit.GRAMME },
    { name: 'Haricots blancs', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 139, unit: Unit.GRAMME },
    { name: 'Fèves', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 110, unit: Unit.GRAMME },
    { name: 'Soja', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 173, unit: Unit.GRAMME },
    { name: 'Edamame', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 121, unit: Unit.GRAMME },
    { name: 'Flageolets', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 128, unit: Unit.GRAMME },
    { name: 'Haricots noirs', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 132, unit: Unit.GRAMME },
    { name: 'Pois cassés', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 118, unit: Unit.GRAMME }
  ],
  noixEtGraines: [
    { name: 'Amande', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 586, unit: Unit.GRAMME },
    { name: 'Noix', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 661, unit: Unit.GRAMME },
    { name: 'Cacahuète', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 575, unit: Unit.GRAMME },
    { name: 'Noix de cajou', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 561, unit: Unit.GRAMME },
    { name: 'Graine de tournesol', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 586, unit: Unit.GRAMME },
    { name: 'Graine de citrouille', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 539, unit: Unit.GRAMME },
    { name: 'Sésame', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 571, unit: Unit.GRAMME },
    { name: 'Noix de pécan', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 700, unit: Unit.GRAMME },
    { name: 'Pistache', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 568, unit: Unit.GRAMME },
    { name: 'Noisette', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 636, unit: Unit.GRAMME },
    { name: 'Noix de macadamia', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 729, unit: Unit.GRAMME },
    { name: 'Graine de lin', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 536, unit: Unit.GRAMME },
    { name: 'Graine de chia', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 493, unit: Unit.GRAMME }
  ],
  herbesEtEpices: [
    { name: 'Basilic', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 50, unit: Unit.GRAMME },
    { name: 'Persil', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 25, unit: Unit.GRAMME },
    { name: 'Coriandre', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 25, unit: Unit.GRAMME },
    { name: 'Thym', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 100, unit: Unit.GRAMME },
    { name: 'Romarin', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 67, unit: Unit.GRAMME },
    { name: 'Origan', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 167, unit: Unit.GRAMME },
    { name: 'Cannelle', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 231, unit: Unit.GRAMME },
    { name: 'Cumin', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 381, unit: Unit.GRAMME },
    { name: 'Paprika', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 261, unit: Unit.GRAMME },
    { name: 'Curry', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 300, unit: Unit.GRAMME },
    { name: 'Safran', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 143, unit: Unit.GRAMME },
    { name: 'Gingembre', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 100, unit: Unit.GRAMME },
    { name: 'Muscade', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 273, unit: Unit.GRAMME },
    { name: 'Cardamome', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 300, unit: Unit.GRAMME },
    { name: 'Anis étoilé', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 250, unit: Unit.GRAMME },
    { name: 'Clou de girofle', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 300, unit: Unit.GRAMME },
    { name: 'Curcuma', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 286, unit: Unit.GRAMME },
    { name: 'Aneth', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 33, unit: Unit.GRAMME }
  ],
  condimentsEtSauces: [
    { name: 'Ketchup', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 100, unit: Unit.GRAMME },
    { name: 'Moutarde', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 60, unit: Unit.GRAMME },
    { name: 'Mayonnaise', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: true, caloriesPer100g: 671, unit: Unit.GRAMME },
    { name: 'Sauce soja', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 50, unit: Unit.MILLILITRE },
    { name: 'Vinaigre balsamique', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 88, unit: Unit.MILLILITRE },
    { name: 'Huile d\'olive', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 850, unit: Unit.MILLILITRE },
    { name: 'Pesto', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 387, unit: Unit.GRAMME },
    { name: 'Sauce Worcestershire', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 100, unit: Unit.MILLILITRE },
    { name: 'Tabasco', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 0, unit: Unit.MILLILITRE },
    { name: 'Sauce barbecue', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 171, unit: Unit.GRAMME },
    { name: 'Sauce tomate', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 25, unit: Unit.GRAMME },
    { name: 'Sauce béchamel', glutenFree: false, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 107, unit: Unit.GRAMME },
    { name: 'Sauce hollandaise', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 493, unit: Unit.GRAMME }
  ],
  boissons: [
    { name: 'Eau', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 0, unit: Unit.MILLILITRE },
    { name: 'Café', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 1, unit: Unit.MILLILITRE },
    { name: 'Thé', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 1, unit: Unit.MILLILITRE },
    { name: 'Jus d\'orange', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 47, unit: Unit.MILLILITRE },
    { name: 'Vin', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: true, caloriesPer100g: 83, unit: Unit.MILLILITRE },
    { name: 'Bière', glutenFree: false, vegetarian: true, vegan: false, lactoseFree: true, caloriesPer100g: 43, unit: Unit.MILLILITRE },
    { name: 'Lait de coco', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 185, unit: Unit.MILLILITRE },
    { name: 'Cidre', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: true, caloriesPer100g: 59, unit: Unit.MILLILITRE },
    { name: 'Cognac', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 239, unit: Unit.MILLILITRE },
    { name: 'Rhum', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 220, unit: Unit.MILLILITRE },
    { name: 'Vodka', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 220, unit: Unit.MILLILITRE },
    { name: 'Whisky', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 239, unit: Unit.MILLILITRE }
  ],
  produitsSucres: [
    { name: 'Sucre', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 400, unit: Unit.GRAMME },
    { name: 'Miel', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: true, caloriesPer100g: 305, unit: Unit.GRAMME },
    { name: 'Chocolat', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 554, unit: Unit.GRAMME },
    { name: 'Confiture', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 280, unit: Unit.GRAMME },
    { name: 'Sirop d\'érable', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 260, unit: Unit.MILLILITRE },
    { name: 'Caramel', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 300, unit: Unit.GRAMME },
    { name: 'Gelée', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: true, caloriesPer100g: 250, unit: Unit.GRAMME },
    { name: 'Pâte d\'amande', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 700, unit: Unit.GRAMME },
    { name: 'Pâte à tartiner', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 540, unit: Unit.GRAMME },
    { name: 'Crème de marrons', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 223, unit: Unit.GRAMME }
  ],
  produitsVegetariens: [
    { name: 'Tofu', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 76, unit: Unit.GRAMME },
    { name: 'Tempeh', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 116, unit: Unit.GRAMME },
    { name: 'Seitan', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 154, unit: Unit.GRAMME },
    { name: 'Lait d\'amande', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 13, unit: Unit.MILLILITRE },
    { name: 'Lait de soja', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 33, unit: Unit.MILLILITRE },
    { name: 'Fromage végétal', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 250, unit: Unit.GRAMME },
    { name: 'Protéines de soja texturées', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 667, unit: Unit.GRAMME },
    { name: 'Jackfruit', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 95, unit: Unit.GRAMME },
    { name: 'Steak végétal', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 168, unit: Unit.GRAMME },
    { name: 'Yaourt végétal', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 41, unit: Unit.GRAMME }
  ],
  alimentsTransformes: [
    { name: 'Pizza', glutenFree: false, vegetarian: false, vegan: false, lactoseFree: false, caloriesPer100g: 266, unit: Unit.GRAMME },
    { name: 'Lasagne', glutenFree: false, vegetarian: false, vegan: false, lactoseFree: false, caloriesPer100g: 115, unit: Unit.GRAMME },
    { name: 'Quiche', glutenFree: false, vegetarian: false, vegan: false, lactoseFree: false, caloriesPer100g: 221, unit: Unit.GRAMME },
    { name: 'Sushi', glutenFree: false, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 250, unit: Unit.GRAMME },
    { name: 'Burger', glutenFree: false, vegetarian: false, vegan: false, lactoseFree: false, caloriesPer100g: 208, unit: Unit.GRAMME },
    { name: 'Frites', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 312, unit: Unit.GRAMME },
    { name: 'Nuggets de poulet', glutenFree: false, vegetarian: false, vegan: false, lactoseFree: false, caloriesPer100g: 308, unit: Unit.GRAMME }
  ],
  ingredientsDeBase: [
    { name: 'Farine', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 379, unit: Unit.GRAMME },
    { name: 'Levure', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 325, unit: Unit.GRAMME },
    { name: 'Bicarbonate de soude', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 0, unit: Unit.GRAMME },
    { name: 'Sel', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 0, unit: Unit.GRAMME },
    { name: 'Poivre', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 261, unit: Unit.GRAMME },
    { name: 'Bouillon', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 4, unit: Unit.MILLILITRE },
    { name: 'Chapelure', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 400, unit: Unit.GRAMME },
    { name: 'Fécule de maïs', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 381, unit: Unit.GRAMME },
    { name: 'Gélatine', glutenFree: true, vegetarian: false, vegan: false, lactoseFree: true, caloriesPer100g: 329, unit: Unit.GRAMME },
    { name: 'Extrait de vanille', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 286, unit: Unit.GRAMME },
    { name: 'Cacao en poudre', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 240, unit: Unit.GRAMME },
    { name: 'Levure chimique', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 50, unit: Unit.GRAMME },
    { name: 'Vinaigre', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 20, unit: Unit.MILLILITRE },
    { name: 'Huile de tournesol', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 886, unit: Unit.MILLILITRE },
    { name: 'Huile de colza', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 886, unit: Unit.MILLILITRE },
    { name: 'Huile de sésame', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 882, unit: Unit.MILLILITRE },
    { name: 'Huile de noix', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 886, unit: Unit.MILLILITRE },
    { name: 'Huile d\'olive', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 881, unit: Unit.MILLILITRE },
    { name: 'Sauce soja', glutenFree: false, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 53, unit: Unit.MILLILITRE },
    { name: 'Moutarde', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 60, unit: Unit.GRAMME },
    { name: 'Ketchup', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 100, unit: Unit.GRAMME },
    { name: 'Mayonnaise', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: true, caloriesPer100g: 681, unit: Unit.GRAMME },
    { name: 'Pesto', glutenFree: true, vegetarian: true, vegan: false, lactoseFree: false, caloriesPer100g: 387, unit: Unit.GRAMME },
    { name: 'Sauce tomate', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 25, unit: Unit.GRAMME },
    { name: 'Sauce barbecue', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 91, unit: Unit.GRAMME },
    { name: 'Sauce aigre-douce', glutenFree: true, vegetarian: true, vegan: true, lactoseFree: true, caloriesPer100g: 110, unit: Unit.MILLILITRE }
  ]
};
